title: 2021-ovSYPHERvo-cev-blog
author: ovSYPHERvo
email: jasonb2905@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is my developer blog, page one. I am Jason (ovSYPHERvo), 
  and this is test one. Blah Blah Blah, words words words

# social links
github_username:  ovSYPHERvo # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
